language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - yarn test
after_success:
  - yarn semantic-release
